title: Will Hunter
description: Personal resume and portfolio site for Will Hunter. Built with Jekyll and hosted on GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  repository_url: https://github.com/whunter1210/whunter1210.github.io